#!/usr/bin/env bash
# hash.sh — compute two independent digests for every file under /canonical/
# and maintain the hash manifests:
#
#   HASHES.txt            SHA-512   (sha512sum format: verify with `sha512sum -c HASHES.txt`)
#   HASHES.sha3-512.txt   SHA3-512  (same layout; verify with scripts/hash.sh --check or
#                                    `openssl dgst -sha3-512 -r <file>`)
#
# Two digest families are published so that a break of either one alone does
# not let a substituted text pass. SHA-512 is primary because every platform
# ships a verifier for it.
#
#   scripts/hash.sh            same as --check
#   scripts/hash.sh --check    verify both manifests against the files; fail on any
#                              changed or missing file; report (but allow) new files
#   scripts/hash.sh --write    verify as above, then append new files to both manifests
#
# Rules this script enforces (see README "Immutability"):
#   * a file listed in a manifest must still exist with the same digests;
#   * a canonical text may only ever be ADDED under a new filename that carries
#     its revision number; it is never edited, renamed or deleted.
# There is deliberately no --force. If a listed digest no longer matches, the
# only correct action is to restore the file.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CANON="$ROOT/canonical"
MODE="${1:---check}"
case "$MODE" in --check|--write) ;; *) echo "usage: $0 [--check|--write]" >&2; exit 2;; esac
[ -d "$CANON" ] || { echo "hash.sh: $CANON does not exist" >&2; exit 1; }
command -v openssl >/dev/null || { echo "hash.sh: openssl is required for SHA3-512" >&2; exit 1; }

tmp512="$(mktemp)"; tmp3="$(mktemp)"; trap 'rm -f "$tmp512" "$tmp3"' EXIT
cd "$ROOT"
# Deterministic order: bytewise sort of paths.
mapfile -d '' FILES < <(find canonical -type f ! -name '.gitkeep' -print0 | LC_ALL=C sort -z)
for f in "${FILES[@]}"; do
  printf '%s  %s\n' "$(sha512sum "$f" | cut -d' ' -f1)" "$f" >> "$tmp512"
  printf '%s  %s\n' "$(openssl dgst -sha3-512 -r "$f" | cut -d' ' -f1)" "$f" >> "$tmp3"
done
touch "$tmp512" "$tmp3"

status=0
check_manifest() { # $1 = manifest path, $2 = current digests file, $3 = label
  local manifest="$1" current="$2" label="$3"
  [ -f "$manifest" ] || return 0
  while read -r hash path; do
    [ -z "$hash" ] && continue; case "$hash" in \#*) continue;; esac
    now="$(awk -v p="$path" '$2==p {print $1}' "$current")"
    if [ -z "$now" ]; then
      echo "hash.sh: MISSING  $path (listed in $(basename "$manifest") but not present; canonical files are never removed or renamed)" >&2
      status=1
    elif [ "$now" != "$hash" ]; then
      echo "hash.sh: CHANGED  $path ($label)" >&2
      echo "           recorded $hash" >&2
      echo "           current  $now" >&2
      echo "           A canonical text is never edited in place. Restore the file; add new text as a new revision filename." >&2
      status=1
    fi
  done < "$manifest"
}
check_manifest "$ROOT/HASHES.txt" "$tmp512" "SHA-512"
check_manifest "$ROOT/HASHES.sha3-512.txt" "$tmp3" "SHA3-512"

if [ -f "$ROOT/HASHES.txt" ]; then
  while read -r hash path; do
    grep -qF -- "  $path" "$ROOT/HASHES.txt" || echo "hash.sh: NEW      $path"
  done < "$tmp512"
fi
[ "$status" -eq 0 ] || { echo "hash.sh: FAILED — canonical integrity violated" >&2; exit 1; }

if [ "$MODE" = "--write" ]; then
  {
    echo "# SHA-512 of every file under /canonical/. Generated by scripts/hash.sh."
    echo "# Verify: sha512sum -c HASHES.txt        (a second, independent manifest is HASHES.sha3-512.txt)"
    echo "# Entries are only ever appended. A changed digest for an existing path fails the build."
    cat "$tmp512"
  } > "$ROOT/HASHES.txt"
  {
    echo "# SHA3-512 of every file under /canonical/. Generated by scripts/hash.sh."
    echo "# Verify: while read h p; do [ \"\${h#\\#}\" = \"\$h\" ] && [ \"\$(openssl dgst -sha3-512 -r \"\$p\" | cut -d' ' -f1)\" = \"\$h\" ] && echo \"ok \$p\"; done < HASHES.sha3-512.txt"
    echo "# Entries are only ever appended. A changed digest for an existing path fails the build."
    cat "$tmp3"
  } > "$ROOT/HASHES.sha3-512.txt"
  echo "hash.sh: wrote ${#FILES[@]} entries to HASHES.txt and HASHES.sha3-512.txt"
else
  if [ -f "$ROOT/HASHES.txt" ] && [ -f "$ROOT/HASHES.sha3-512.txt" ]; then
    echo "hash.sh: OK — $(grep -vc '^#' "$ROOT/HASHES.txt" || true) recorded entries verified against both manifests"
  else
    echo "hash.sh: manifests not present yet; run scripts/hash.sh --write" >&2; exit 1
  fi
fi
